<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrOC1TU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrOC1TU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPrOC1TU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPrOC1TU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPrOC1TU\App_KernelDevDebugContainer([
    'container.build_hash' => 'PrOC1TU',
    'container.build_id' => '0390161f',
    'container.build_time' => 1583705135,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrOC1TU');
